BASE_DOMAIN: ${ BASE_DOMAIN }
CMS_HOST: studio.local.edly.io
CONTACT_EMAIL: help@thegymnasium.com
DOCKER_IMAGE_OPENEDX: "gymnasium/gym-theme-openedx:{{ TUTOR_VERSION }}"
DOCKER_IMAGE_OPENEDX_DEV: "gymnasium/gym-theme-openedx-dev:{{ TUTOR_VERSION }}"
ENABLE_HTTPS: false
ENABLE_WEB_PROXY: false
FEATURES:
- ENABLE_MKTG_SITE: true
LMS_HOST: local.edly.io
MARKETING_SITE_BASE_URL: ${ MARKETING_SITE_BASE_URL }
MFE_DOCKER_IMAGE: "gymnasium/gym-theme-mfe:{{ TUTOR_VERSION }}"
MFE_DOCKER_IMAGE_DEV_PREFIX: "gymnasium/gym-theme"
MOUNTS:
- ./mfe/frontend-app-authn
- authn:./mfe/gym-frontend-components:/openedx/app/@edx/gym-frontend
- authn:./mfe/module.config.js:/openedx/app/module.config.js
- ./mfe/frontend-app-course-about
- course-about:./mfe/gym-frontend-components:/openedx/app/@edx/gym-frontend
- course-about:./mfe/module.config.js:/openedx/app/module.config.js
- ./mfe/frontend-app-learner-dashboard
- learner-dashboard:./mfe/gym-frontend-components:/openedx/app/@edx/gym-frontend
- learner-dashboard:./mfe/module.config.js:/openedx/app/module.config.js
OPENEDX_EXTRA_PIP_REQUIREMENTS:
- git+https://github.com/gymnasium/custom_registration_form@feat/quince#egg=custom_reg_form
PLATFORM_NAME: Gymnasium
PLUGINS:
- caddy-csp
- course-about-dev
- custom-reg-form
- forum
- gym-theme
- mfe
- mfe-disable
- mfe-forks
- shared-cookies
PREVIEW_LMS_HOST: preview.local.edly.io
SESSION_COOKIE_DOMAIN: ${ BASE_DOMAIN }
SHARED_COOKIE_DOMAIN: ${ BASE_DOMAIN }
