BASE_DOMAIN: gym.soy
CMS_HOST: studio.learn.gym.soy
CONTACT_EMAIL: help@thegymnasium.com
DOCKER_IMAGE_OPENEDX: "gymnasium/gym-theme-openedx:{{ TUTOR_VERSION }}"
DOCKER_IMAGE_OPENEDX_DEV: "gymnasium/gym-theme-openedx-dev:{{ TUTOR_VERSION }}"
ENABLE_HTTPS: true
ENABLE_WEB_PROXY: false
FEATURES:
- ENABLE_MKTG_SITE: true
LMS_HOST: learn.gym.soy
MARKETING_SITE_BASE_URL: https://gym.soy
MFE_DOCKER_IMAGE: "gymnasium/gym-theme-mfe:{{ TUTOR_VERSION }}"
MFE_DOCKER_IMAGE_DEV_PREFIX: "gymnasium/gym-theme"
OPENEDX_EXTRA_PIP_REQUIREMENTS:
- git+https://github.com/gymnasium/custom_registration_form@feat/quince#egg=custom_reg_form
PLATFORM_NAME: Gymnasium
PLUGINS:
- caddy-csp
- course-about-prod
- custom-reg-form
- forum
- gym-theme
- mfe
- mfe-disable
- mfe-forks
- shared-cookies
PREVIEW_LMS_HOST: preview.learn.gym.soy
SESSION_COOKIE_DOMAIN: gym.soy
SHARED_COOKIE_DOMAIN: gym.soy
