CAIRN_CLICKHOUSE_PASSWORD: eGUhQbWMRSKSrB6LJqPl
CAIRN_POSTGRESQL_PASSWORD: KQY1VDAkTPKZz0bAi9J9
CAIRN_SSO_CLIENT_SECRET: 7ojP8DylFPiJN83O46VL
CAIRN_SUPERSET_SECRET_KEY: WcbX8dsobUWH5zOgHDz4
CMS_HOST: studio.local.overhang.io
CMS_OAUTH2_SECRET: 2icx54cdu9SJ77KMlZgHTWcm
CONTACT_EMAIL: help@thegymnasium.com
DOCKER_IMAGE_OPENEDX: docker.io/gymnasium/gym-theme-openedx:16.1.8
ENABLE_HTTPS: false
ENABLE_WEB_PROXY: true
ID: jxBish2U54zbLTe82GMVvnyO
JWT_RSA_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----

  MIIEogIBAAKCAQEAsK382wJ5KwASG0Fn2eCaSQr48VcOTOPt3V5noe/b6pJN7EPp

  zhHaKOHIcwE6Ux4YAObiOz8IjaAhp0cM28vBI3gUp6b39alV7lY5Zb5WIm0B4SvA

  NycymKDvx34rurLEptLem18roh8CaSIvyHD2/wnafjmeSRyUdfB6HDGP294vnlRK

  wNjeEQ9WHSa4BoE4T7j9QOd/gQrHHaiXOEKbVfz+fif7t6jqUEBNShF3yPaWollJ

  mLNwRPhQGMbFLDab0qC/loPwhsSeEIgDUM1oNCHZmJbvlK6uRRqiRKpKVr+Ggssh

  9I9qk2vnQT9+MGfvm5nb5MjfR5iKSIQiQ1s3ywIDAQABAoIBABrlVvlyy5tI1s4g

  ticsJ+XirmRJn7sDdQcerfawRZwp9YQiuomiR2xdzV6khd/NVFN0J7sOght9Owz0

  pffNHB5tffIfsDOiOZtKCPwnbi6uGtElEI0qLGuhDvTMN5VOTYglJbolUhvLTgSk

  gv2nz2dNIAktyvN6Tvy9RPmHGffwVAfM3ROvuiToLiMvExPJxvZ63evuegmA9pO7

  Wasnxxwm7RpF1J/GOx2pZ0kpu3c1F+BzrLdWRMXuwzmLf+RajVcnXix4qLgLEtBp

  hktviT2rL05IHEFzAMXm4rwz2gvSOyXKz9JbhX+0VBwK2bv9TbYAT06rIYPKYVlY

  /VSNI7ECgYEAxdl6uY2DFCOCQLdVSf/CTLt3ai2cp938kYkdOSqCX5UnSONwkJQX

  JLxwyUg4Kp1QtNPa434Misq+zQtG8mWpyRCo55cU60WWEubN9nuiTQI0PuW1sk57

  032f8XiW2i20wi6wzQLxUkPl4EbF840sNB16UtuvL8IkAmxv/Ocif2cCgYEA5Jum

  wVdozG0kChtJrq8nv0iZHZ5BiYL9PMxqlucsNA6eFK+qSrcKWbBdgptn1Z9pNh6Z

  KGROAf0rm9lxR7PtPmq9mJIZ60BvN/ykaMXlhDLS6P3+Irxw9oC8Nac2mlYgvbmL

  wiOr0XDaAhxSOCDNoADMwdaorMK3cIQkZZtz2f0CgYAY5l4DrEOq7S0fZ/Nb9MxH

  S/CjdEoa9l0rE86Ruz/dN7BSBA3OpFSlUvH+4w/ujQ3zNBaAOwTpEssgkyLCrvjH

  TUl0nBcN5RwWFOYm9zhd6MEaiV5sqmP7IfxXL44Mt2PgbG/j3VLxv4nWyBFxrXq6

  tFsIwo0xvYU6qNsPQSeeUQKBgGuhGJ54T7/HNquHc2ZJ0rXNMUFvi715LU7dkuVf

  C0GrDCQDHHK2wKm/Thc6oWVC+x7eww7wQoXPMyPZ+OpgPLchPAhD6O4IVRSP3rvx

  SAC4iPHm+ypRfAGiVHoSMrPxDtMkMzeA4djmf810lgUU9Jp7Jeuw65MCzaisnhI0

  YRPlAoGAcaBiNjjhDw/DX6MPb3ICbZBDiI1Kz+tg9qpfLzpgoFmvhg8ij6knAjsf

  N3iAEqSeiUrgt75DlvfFNN3DMPgEV4ISvbSR6pzF0OrrfVV9ELWkIu/YTwOM8dEb

  +aJ0hXSsVIp99Jyamo1RdyJXWEVm48NvM2RLH+JxvGNMK7oT/8o=

  -----END RSA PRIVATE KEY-----'
LANGUAGE_CODE: en
LMS_HOST: local.overhang.io
MARKETING_SITE_BASE_URL: http://local.overhang.io
MARKETING_SITE_ROOT: http://local.overhang.io
MFE_ACCOUNT_MFE_APP:
  name: account
  port: 1997
  repository: https://github.com/gymnasium/frontend-app-account
  version: gym.quince.1
MFE_AUTHN_MFE_APP:
  name: authn
  port: 1999
  repository: https://github.com/gymnasium/frontend-app-authn
  version: gym.quince.1
MFE_COURSE_ABOUT_MFE_APP:
  name: course-about
  port: 3000
  repository: https://github.com/gymnasium/frontend-app-course-about
  version: gym.quince.1
MFE_DISCUSSIONS_MFE_APP:
  name: discussions
  port: 2002
  repository: https://github.com/gymnasium/frontend-app-discussions
  version: gym.quince.1
MFE_DOCKER_IMAGE: docker.io/gymnasium/gym-theme-mfe:16.1.8
MFE_LEARNER_DASHBOARD_MFE_APP:
  name: learner-dashboard
  port: 1996
  repository: https://github.com/gymnasium/frontend-app-learner-dashboard
  version: gym.quince.1
MFE_LEARNING_MFE_APP:
  name: learning
  port: 2000
  repository: https://github.com/gymnasium/frontend-app-learning
  version: gym.quince.1
MFE_PROFILE_MFE_APP:
  name: profile
  port: 1995
  repository: https://github.com/gymnasium/frontend-app-profile
  version: gym.quince.1
MOUNTS:
- ./mfe/frontend-app-account
- ./mfe/frontend-app-authn
- ./mfe/frontend-app-course-about
- ./mfe/frontend-app-discussions
- ./mfe/frontend-app-learner-dashboard
- ./mfe/frontend-app-learning
- ./mfe/frontend-app-profile
- account:./mfe/gym-frontend-components:/openedx/app/src/gym-frontend-components
- authn:./mfe/gym-frontend-components:/openedx/app/src/gym-frontend-components
- course-about:./mfe/gym-frontend-components:/openedx/app/src/gym-frontend-components
- discussions:./mfe/gym-frontend-components:/openedx/app/src/gym-frontend-components
- learner-dashboard:./mfe/gym-frontend-components:/openedx/app/src/gym-frontend-components
- learning:./mfe/gym-frontend-components:/openedx/app/src/gym-frontend-components
- profile:./mfe/gym-frontend-components:/openedx/app/src/gym-frontend-components
MYSQL_ROOT_PASSWORD: 43Lfuln2
OPENEDX_MYSQL_PASSWORD: 2waV0m9w
OPENEDX_SECRET_KEY: eHqeglW5j7T68yYtr3yL6XPz
PLATFORM_NAME: Gymnasium
PLUGINS:
- course-about-mfe
- custom
- forum
- gym-cors
- gym-mfe
- gym-theme
PLUGIN_INDEXES:
- https://overhang.io/tutor/main
PREVIEW_LMS_HOST: preview.local.overhang.io
